export const ActionTypes = {
    USER_LOADING : 'USER_LOADING',
    USER_LOADED : 'USER_LOADED',
    AUTH_ERROR : 'AUTH_ERROR',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAIL : 'LOGIN_FAIL',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    REGISTER_SUCCESS : 'REGISTER_SUCCESS',
    REGISTER_FAIL : 'REGISTER_FAIL',

    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    FETCH_PRODUCT : 'FETCH_PRODUCT',

    FETCH_CART : 'FETCH_CART',
    CART_LOADING : 'CART_LOADING',
}
